[package]
name = "vodozemac-javascript"
version = "0.1.0"
edition = "2021"

[lib]
name = "vodozemac"
crate-type = ["cdylib"]

[dependencies]
vodozemac = { workspace = true, features = ["js"] }
wasm-bindgen = "0.2.92"
js-sys = "0.3.69"
serde-wasm-bindgen = "0.6.5"
